#!/usr/bin/env python3
"""Generate image_prompts.json for all remaining themes."""
import json
from pathlib import Path

prompts = {
    'deep-sea': {
        'bg': {
            'bg-5.jpg': 'Vibrant coral reef with colorful corals, tropical fish, sun rays piercing water, underwater game background, 16:9',
            'bg-6.jpg': 'Kelp forest with tall seaweed, sunbeams filtering through, fish swimming, underwater game bg, 16:9',
            'bg-7.jpg': 'Sunken shipwreck resting on ocean floor, coral-covered, beams of light filtering, underwater bg, 16:9',
            'bg-8.jpg': 'Underwater volcano venting black smoke, strange tube worms, volcanic rock formations, underwater bg, 16:9',
            'bg-9.jpg': 'Ice cavern underwater with blue light, ice formations, mysterious glow, underwater exploration bg, 16:9',
            'bg-10.jpg': 'Deep sea canyon with steep walls, fish silhouettes in distance, dark blue water, underwater bg, 16:9',
            'bg-11.jpg': 'Underwater grotto with air pocket, stalactites hanging, crystal clear pool, hidden cave bg, 16:9',
            'bg-12.jpg': 'Sunken city with stone buildings and statues covered in coral, ancient ruins, underwater bg, 16:9',
            'bg-13.jpg': 'Hydrothermal vent field with smoke plumes, strange tubeworms and life forms, deep sea bg, 16:9',
            'bg-14.jpg': 'Underwater temple with stone arches and columns, glowing symbols on walls, mystical game bg, 16:9',
        },
        'char': {
            'char-0.jpg': 'Scuba diver with oxygen tank, mask, fins, exploring underwater, marine character portrait',
            'char-1.jpg': 'Beautiful mermaid with colorful fish tail, long flowing hair, mystical underwater character',
            'char-2.jpg': 'Giant octopus with massive tentacles spread, huge eyes, deep sea creature portrait',
            'char-3.jpg': 'Friendly dolphin leaping above water, sleek gray body, intelligent eyes, marine animal portrait',
            'char-4.jpg': 'Great white shark with mouth open showing rows of sharp teeth, predator creature portrait',
            'char-5.jpg': 'Giant sea turtle with patterned shell, wise old face, swimming gracefully, animal portrait',
            'char-6.jpg': 'Deep sea anglerfish with glowing lure on head, sharp teeth, eerie creature portrait',
            'char-7.jpg': 'Submarine pilot in yellow diving suit, inside sub control room, character portrait',
            'char-8.jpg': 'Bioluminescent jellyfish with long trailing tentacles, glowing, graceful creature portrait',
            'char-9.jpg': 'Giant squid emerging from deep darkness, huge eyes, tentacles reaching, monster portrait',
            'char-10.jpg': 'Crab with large claws, walking on ocean floor, armored shell, crustacean creature portrait',
            'char-11.jpg': 'Mermaid queen with crown made of coral, pearl necklace, regal ruler character portrait',
            'char-12.jpg': 'Moray eel peeking from coral crevice, sharp teeth, spotted body, creature portrait',
            'char-13.jpg': 'Seahorse with curled tail, intricate body pattern, colorful, delicate creature portrait',
            'char-14.jpg': 'Leviathan giant sea serpent coiled in water, massive size, ancient monster portrait',
        },
        'item': {
            'item-0.jpg': 'Shiny pearl inside open oyster shell, iridescent, treasure on dark background',
            'item-1.jpg': 'Harpoon gun with barbed metal tip, underwater hunting weapon on dark background',
            'item-2.jpg': 'Diving mask with glass faceplate and snorkel tube, equipment on dark background',
            'item-3.jpg': 'Wooden treasure chest open with gold coins spilling out, pirate treasure on dark',
            'item-4.jpg': 'Old ship anchor with heavy chain, rusted metal, nautical item on dark background',
            'item-5.jpg': 'Pink coral branch with intricate structure, marine organism on dark background',
            'item-6.jpg': 'Glass message in a bottle with cork stopper, paper visible inside, on dark',
            'item-7.jpg': 'Ship steering wheel with wooden spokes, brass hub, nautical wheel on dark',
            'item-8.jpg': 'Golden trident with three sharp prongs, sea god weapon on dark background',
            'item-9.jpg': 'Orange starfish with five arms, textured surface, marine creature on dark',
            'item-10.jpg': 'Scuba oxygen tank with valve and regulator, metal cylinder on dark background',
            'item-11.jpg': 'Swim flippers with foot pockets, black rubber, diving gear on dark background',
            'item-12.jpg': 'Underwater camera with waterproof housing, flash, photography on dark background',
            'item-13.jpg': 'Spiral conch shell with pink interior opening, seashell on dark background',
            'item-14.jpg': 'Ancient stone tablet with underwater carvings and symbols, ruins on dark',
        },
    },
    'tomb-raiding': {
        'bg': {
            'bg-5.jpg': 'Pyramid exterior at sunset, massive stone blocks, desert sand, dramatic sky, adventure game bg, 16:9',
            'bg-6.jpg': 'Long torch-lit corridor with hieroglyphics on walls, stone floor, adventure game bg, 16:9',
            'bg-7.jpg': 'Trap room with pressure plates on floor, dart holes in walls, skeletons, adventure bg, 16:9',
            'bg-8.jpg': 'Underground crypt with stone sarcophagi against walls, dim torch light, adventure bg, 16:9',
            'bg-9.jpg': 'Offering chamber filled with golden artifacts, statues, piles of treasure, adventure bg, 16:9',
            'bg-10.jpg': 'Grand stone stairway carved into rock, descending into darkness below, adventure bg, 16:9',
            'bg-11.jpg': 'Hall of massive stone pillars with torch light casting shadows, adventure game bg, 16:9',
            'bg-12.jpg': 'Inner sanctum with glowing sarcophagus emitting mystical light, adventure game bg, 16:9',
            'bg-13.jpg': 'Temple entrance with massive stone doors, carved snakes, jungle surroundings, adventure bg, 16:9',
            'bg-14.jpg': 'Altar room with stone altar, golden idol, ritual candles, mysterious game bg, 16:9',
        },
        'char': {
            'char-0.jpg': 'Adventurer archaeologist with fedora hat, leather jacket, whip, character portrait',
            'char-1.jpg': 'Local guide in traditional desert clothes, carrying a map, helpful character portrait',
            'char-2.jpg': 'Bandaged mummy with wraps unraveling, glowing eyes, undead horror creature portrait',
            'char-3.jpg': 'Golden scarab beetle with jeweled shell, ancient Egyptian icon, animal portrait',
            'char-4.jpg': 'Anubis warrior with jackal head, holding a staff, guardian character portrait',
            'char-5.jpg': 'Tomb raider with climbing gear, backpack, determined expression, action character portrait',
            'char-6.jpg': 'Pharaoh mummy with golden death mask, royal striped headdress, ruler portrait',
            'char-7.jpg': 'Giant scorpion with stinger raised high, large pincers, desert creature portrait',
            'char-8.jpg': 'Snake charmer with turban on head, playing flute for cobra, character portrait',
            'char-9.jpg': 'Stone gargoyle statue with wings spread, frozen in time, guardian statue portrait',
            'char-10.jpg': 'Expedition leader with khaki safari clothes, binoculars, hat, explorer character',
            'char-11.jpg': 'Bactrian camel with two humps, saddle, desert transportation animal portrait',
            'char-12.jpg': 'Cursed spirit with glowing eyes, tattered ancient robes, floating ghost portrait',
            'char-13.jpg': 'Tomb guardian in golden armor with spear and shield, warrior character portrait',
            'char-14.jpg': 'Giant python constrictor coiled, patterned scales, predator reptile portrait',
        },
        'item': {
            'item-0.jpg': 'Small golden idol statue with jeweled eyes, treasure artifact on dark background',
            'item-1.jpg': 'Leather bullwhip coiled, braided leather, handle, tool on dark background',
            'item-2.jpg': 'Ancient papyrus map showing tomb layout with markings, paper on dark background',
            'item-3.jpg': 'Ornate golden key with decorative head, ancient door key on dark background',
            'item-4.jpg': 'Winged scarab amulet in turquoise and gold, Egyptian jewelry on dark background',
            'item-5.jpg': 'Golden ankh cross symbol with looped top, Egyptian icon on dark background',
            'item-6.jpg': 'Burning torch with orange flame on wooden stick, light source on dark background',
            'item-7.jpg': 'Painted sarcophagus with pharaoh face, gold details, coffin on dark background',
            'item-8.jpg': 'Jeweled golden chalice or cup, precious treasure on dark background',
            'item-9.jpg': 'Stone tablet with carved hieroglyphics and symbols, ancient on dark background',
            'item-10.jpg': 'Coiled rope with metal grappling hook, climbing tool on dark background',
            'item-11.jpg': 'Brass compass with glass face and needle, navigation tool on dark background',
            'item-12.jpg': 'Transparent crystal skull, mysterious artifact on dark background',
            'item-13.jpg': 'Pile of gold coins with hieroglyphic edges, treasure on dark background',
            'item-14.jpg': 'Ancient rolled scroll with red wax seal, document on dark background',
        },
    },
    'apocalypse': {
        'bg': {
            'bg-5.jpg': 'Abandoned highway with rusted cars, cracked asphalt, overgrown vegetation, post-apocalyptic game bg, 16:9',
            'bg-6.jpg': 'Ruined shopping mall with collapsed ceiling, looted stores, debris, survival game bg, 16:9',
            'bg-7.jpg': 'Abandoned hospital interior with gurneys, medical equipment, dark hallways, survival game bg, 16:9',
            'bg-8.jpg': 'Survivor camp with tents, campfire, makeshift shelters, fences, post-apocalyptic game bg, 16:9',
            'bg-9.jpg': 'Abandoned power plant with cooling towers, rusted pipes, industrial decay, game bg, 16:9',
            'bg-10.jpg': 'Dark subway tunnel with graffiti, abandoned train, garbage, survival game bg, 16:9',
            'bg-11.jpg': 'Collapsed bridge over dry riverbed, twisted metal, broken concrete, game bg, 16:9',
            'bg-12.jpg': 'Rooftop garden with vegetable plants, water barrels, solar panels, survivor base bg, 16:9',
            'bg-13.jpg': 'Sewer tunnel with flowing water, pipes, moss, dark, survival game background, 16:9',
            'bg-14.jpg': 'Military outpost with barbed wire, sandbags, watchtower, bunker entrance, game bg, 16:9',
        },
        'char': {
            'char-0.jpg': 'Rugged survivor with backpack, gas mask around neck, scarred face, character portrait',
            'char-1.jpg': 'Fellow survivor with goggles, scarf, carrying a crowbar, companion character portrait',
            'char-2.jpg': 'Mutated creature with glowing eyes, deformed body, claws, horror monster portrait',
            'char-3.jpg': 'Mangy mutated dog with patchy fur, yellow eyes, aggressive stance, animal portrait',
            'char-4.jpg': 'Militia soldier in combat gear with rifle, helmet, tactical vest, soldier portrait',
            'char-5.jpg': 'Doctor in bloodstained white coat, glasses, exhausted expression, survivor portrait',
            'char-6.jpg': 'Scavenger with gas mask, backpack full of loot, crouching, character portrait',
            'char-7.jpg': 'Raider with leather armor, spiked shoulder pads, carrying a bat, villain portrait',
            'char-8.jpg': 'Elderly survivor with walking stick, white beard, wise weathered face, portrait',
            'char-9.jpg': 'Giant mutated rat with red eyes, sharp teeth, diseased fur, creature portrait',
            'char-10.jpg': 'Child survivor with teddy bear, dirty face, scared but brave expression, portrait',
            'char-11.jpg': 'Mechanic with welding goggles, tool belt, oil-stained clothes, character portrait',
            'char-12.jpg': 'Zombie-like infected with pale skin, black veins, reaching arms, creature portrait',
            'char-13.jpg': 'Hunter with bow and arrow, camouflage clothes, stealthy, character portrait',
            'char-14.jpg': 'Radiation ghost with translucent green glow, distorted human form, specter portrait',
        },
        'item': {
            'item-0.jpg': 'Crowbar with metal pry bar, tool and weapon on dark background',
            'item-1.jpg': 'Gas mask with round eye pieces, filters, protective gear on dark background',
            'item-2.jpg': 'Water canteen with dirt marks, survival essential on dark background',
            'item-3.jpg': 'First aid kit with red cross, bandages visible, medical on dark background',
            'item-4.jpg': 'Tin of canned food with label peeling, survival food on dark background',
            'item-5.jpg': 'Geiger counter with needle display, clicking, radiation detector on dark',
            'item-6.jpg': 'Combat knife with serrated edge, black handle, weapon on dark background',
            'item-7.jpg': 'Flashlight with bright beam, metal body, light source on dark background',
            'item-8.jpg': 'Radiation pill bottle with label, anti-radiation drug on dark background',
            'item-9.jpg': 'Map of the city with marked routes and safe zones, paper on dark background',
            'item-10.jpg': 'Revolver handgun with wooden grip, six shooter, weapon on dark background',
            'item-11.jpg': 'Metal water bottle dented and scratched, survival gear on dark background',
            'item-12.jpg': 'Binoculars with leather strap, observation tool on dark background',
            'item-13.jpg': 'Supply crate with military markings, wooden box on dark background',
            'item-14.jpg': 'Radio with antenna, communication device on dark background',
        },
    },
    'magic-academy': {
        'bg': {
            'bg-5.jpg': 'School courtyard with fountain in center, stone benches, magical plants, fantasy game bg, 16:9',
            'bg-6.jpg': 'Dormitory room with four-poster beds, glowing candles, starry night window, fantasy bg, 16:9',
            'bg-7.jpg': 'Potions classroom with bubbling cauldrons, ingredient shelves, colored vapors, fantasy bg, 16:9',
            'bg-8.jpg': 'Observatory tower with telescope pointing at stars, astrolabe, magical sky, fantasy bg, 16:9',
            'bg-9.jpg': 'Underground dungeon with cells, chains on walls, dim torch light, fantasy game bg, 16:9',
            'bg-10.jpg': 'Rooftop of the academy with gargoyles, view of mountains, sunset, fantasy game bg, 16:9',
            'bg-11.jpg': 'Enchanted fountain with glowing water, stone nymphs, magical light, fantasy bg, 16:9',
            'bg-12.jpg': 'Main gate of the academy with ironwork, magical torches, entrance, fantasy bg, 16:9',
            'bg-13.jpg': 'Enchanted forest near the academy with glowing trees, fairy lights, fantasy bg, 16:9',
            'bg-14.jpg': 'Secret chamber under the academy with ancient magic circle, glowing runes, fantasy bg, 16:9',
        },
        'char': {
            'char-0.jpg': 'Young wizard student in blue robes, holding a wand, eager expression, character portrait',
            'char-1.jpg': 'Floating magical familiar spirit made of light, small winged creature, companion portrait',
            'char-2.jpg': 'Dark wizard in black hooded robes, red eyes, evil magic crackling, villain portrait',
            'char-3.jpg': 'White owl with wide spread wings, golden eyes, magical messenger animal portrait',
            'char-4.jpg': 'Headmaster wizard with long white beard, starry robes, wise expression, mentor portrait',
            'char-5.jpg': 'Cat familiar with black fur, green eyes, sitting on a spell book, animal portrait',
            'char-6.jpg': 'Phoenix bird with fiery red and gold feathers, rising from flames, mythical portrait',
            'char-7.jpg': 'Sorceress with flowing purple hair, magical aura, casting a spell, character portrait',
            'char-8.jpg': 'Troll guarding the bridge, large club, green skin, dumb expression, creature portrait',
            'char-9.jpg': 'Ghost of a former student, translucent white, floating, sad expression, spirit portrait',
            'char-10.jpg': 'Alchemist with potion belt, goggles, mixing ingredients, eccentric character portrait',
            'char-11.jpg': 'Dragon hatchling with small wings, scales, breathing tiny flame, creature portrait',
            'char-12.jpg': 'Librarian with spectacles, shushing finger, surrounded by floating books, character portrait',
            'char-13.jpg': 'Unicorn with white coat, spiral horn, glowing mane, magical animal portrait',
            'char-14.jpg': 'Golem made of stone and runes, massive body, guardian creature portrait',
        },
        'item': {
            'item-0.jpg': 'Magic wand with spiral handle, glowing tip, spellcasting tool on dark background',
            'item-1.jpg': 'Potion bottle with purple liquid, glass stopper, alchemy on dark background',
            'item-2.jpg': 'Spell book with leather cover, gold runes, open pages on dark background',
            'item-3.jpg': 'Crystal ball on stand, swirling mist inside, divination on dark background',
            'item-4.jpg': 'Broomstick with bristles, flying transport on dark background',
            'item-5.jpg': 'Magic ring with glowing gemstone, enchanted jewelry on dark background',
            'item-6.jpg': 'Cauldron with bubbling green liquid, iron pot, alchemy on dark background',
            'item-7.jpg': 'Owl feather quill pen with ink bottle, writing on dark background',
            'item-8.jpg': 'Scroll of teleportation with magical symbols, parchment on dark background',
            'item-9.jpg': 'Enchanted compass pointing to magic, glowing needle on dark background',
            'item-10.jpg': 'Potion ingredient mortar and pestle, herb grinding on dark background',
            'item-11.jpg': 'Wizard hat with stars pattern, pointed blue hat on dark background',
            'item-12.jpg': 'Amulet of protection with blue gem, necklace on dark background',
            'item-13.jpg': 'Hourglass with glowing sand flowing, time magic on dark background',
            'item-14.jpg': 'Ancient rune stone with carved symbols, magical on dark background',
        },
    },
    'cyberpunk': {
        'bg': {
            'bg-5.jpg': 'Dark alley with neon signs reflecting in puddles, trash, steam vents, cyberpunk game bg, 16:9',
            'bg-6.jpg': 'Night market street stalls, holographic advertisements, crowded, cyberpunk game bg, 16:9',
            'bg-7.jpg': 'Arcade interior with glowing machines, neon strips, gamers, cyberpunk game bg, 16:9',
            'bg-8.jpg': 'Penthouse apartment with floor to ceiling windows, city view, luxury cyberpunk bg, 16:9',
            'bg-9.jpg': 'Sewer tunnel with neon reflections in water, pipes, graffiti, cyberpunk game bg, 16:9',
            'bg-10.jpg': 'Massive suspension bridge connecting city districts, lights, traffic, cyberpunk bg, 16:9',
            'bg-11.jpg': 'Factory interior with robotic arms, conveyor belts, sparks, industrial cyberpunk bg, 16:9',
            'bg-12.jpg': 'Prison cell with energy bars, surveillance cameras, sterile, cyberpunk game bg, 16:9',
            'bg-13.jpg': 'Server room with rows of computers, blue lights, cables, cyberpunk game bg, 16:9',
            'bg-14.jpg': 'Downtown plaza with giant holographic billboards, crowds, futuristic city bg, 16:9',
        },
        'char': {
            'char-0.jpg': 'Hacker with cybernetic eye implant, hoodie, neon hair streaks, character portrait',
            'char-1.jpg': 'AI hologram companion, translucent blue feminine form, digital particles, portrait',
            'char-2.jpg': 'Corporate agent in black suit, sunglasses, earpiece, cold expression, villain portrait',
            'char-3.jpg': 'Robotic cyber dog with metal plates, glowing red eyes, mechanical, animal portrait',
            'char-4.jpg': 'Street samurai with cybernetic arm, katana, armored jacket, warrior portrait',
            'char-5.jpg': 'Netrunner with neural interface cables, VR headset, character portrait',
            'char-6.jpg': 'Cybernetic mercenary with visible metal implants, heavy weapons, soldier portrait',
            'char-7.jpg': 'Neon dancer with LED dress, glowing accessories, performer character portrait',
            'char-8.jpg': 'Drone with camera eye, four rotors, flying, robotic vehicle portrait',
            'char-9.jpg': 'Gang member with cybernetic jaw, leather jacket, tattoos, villain portrait',
            'char-10.jpg': 'Doctor with augmented reality glasses, medical coat, cybernetic character portrait',
            'char-11.jpg': 'Traffic controller with glowing wand, uniform, futuristic helmet, character portrait',
            'char-12.jpg': 'Bounty hunter with visor helmet, rifle, exoskeleton armor, character portrait',
            'char-13.jpg': 'Artificial human with perfect synthetic face, slightly wrong eyes, android portrait',
            'char-14.jpg': 'Riot robot with armored shell, red lights, mechanical arms, machine portrait',
        },
        'item': {
            'item-0.jpg': 'Cyberdeck hacking device with holographic display, tech tool on dark background',
            'item-1.jpg': 'Plasma pistol with glowing blue energy cell, sci-fi weapon on dark background',
            'item-2.jpg': 'Neon sunglasses with reflective lenses, cyberpunk fashion on dark background',
            'item-3.jpg': 'Data chip with holographic light, information storage on dark background',
            'item-4.jpg': 'Holographic map of the city, 3D buildings, projection on dark background',
            'item-5.jpg': 'Cybernetic arm implant with visible wires, metal and chrome on dark background',
            'item-6.jpg': 'Neon katana with glowing blade, energy sword on dark background',
            'item-7.jpg': 'Augmented reality glasses with HUD display, tech eyewear on dark background',
            'item-8.jpg': 'Neural interface plug with wires, cyberpunk implant on dark background',
            'item-9.jpg': 'Credit chip with holographic numbers, currency on dark background',
            'item-10.jpg': 'Smartphone with holographic projection, future tech on dark background',
            'item-11.jpg': 'Graffiti spray can with neon paint, street art on dark background',
            'item-12.jpg': 'Energy drink can with glowing logo, futuristic beverage on dark background',
            'item-13.jpg': 'Stimulant injector with blue liquid, medical device on dark background',
            'item-14.jpg': 'ID card with holographic photo, identification on dark background',
        },
    },
    'lost-civilization': {
        'bg': {
            'bg-5.jpg': 'Step pyramid with stone terraces, jungle vines covering it, ancient ruins, adventure bg, 16:9',
            'bg-6.jpg': 'Stone rope bridge over a deep jungle canyon, mist below, adventure game bg, 16:9',
            'bg-7.jpg': 'Ancient palace interior with stone thrones, faded murals, grand hall, adventure bg, 16:9',
            'bg-8.jpg': 'Astronomical observatory with stone alignments, star charts on walls, ancient bg, 16:9',
            'bg-9.jpg': 'Underground tomb with carved walls, burial offerings, mysterious light, adventure bg, 16:9',
            'bg-10.jpg': 'Grand stone stairway up the side of a temple mountain, misty, adventure game bg, 16:9',
            'bg-11.jpg': 'Sacred fountain plaza with carved stone water channels, mossy, adventure bg, 16:9',
            'bg-12.jpg': 'Massive stone gate with carved faces, jungle entrance, overgrown, adventure bg, 16:9',
            'bg-13.jpg': 'Hidden cave shrine with natural light beam, altar, ancient offerings, adventure bg, 16:9',
            'bg-14.jpg': 'Inner sanctum with glowing crystal power source, advanced tech, mystical bg, 16:9',
        },
        'char': {
            'char-0.jpg': 'Explorer with machete, khaki shirt, hat, determined look, adventurer character portrait',
            'char-1.jpg': 'Native guide with tribal markings on face, carrying bow, character portrait',
            'char-2.jpg': 'Stone guardian statue come to life with glowing eyes, massive, creature portrait',
            'char-3.jpg': 'Black jaguar with golden eyes, sleek body, stealthy predator animal portrait',
            'char-4.jpg': 'Tribal warrior with spear, feathers, body paint, fierce expression, character portrait',
            'char-5.jpg': 'Ancient king skeleton on throne with crown and scepter, mummy ruler portrait',
            'char-6.jpg': 'Giant anaconda snake with thick body, scales, coiled, predator reptile portrait',
            'char-7.jpg': 'Golden eagle with wide wingspan, sharp beak, flying bird of prey portrait',
            'char-8.jpg': 'Howler monkey in tree, making noise, furry primate animal portrait',
            'char-9.jpg': 'Mysterious priest in feathered headdress, ceremonial mask, character portrait',
            'char-10.jpg': 'Parrot with colorful red and blue feathers, tropical bird animal portrait',
            'char-11.jpg': 'Crystal entity made of glowing stone, humanoid shape, being of light portrait',
            'char-12.jpg': 'Ancient spirit guardian with translucent body, glowing eyes, ethereal portrait',
            'char-13.jpg': 'Jaguar warrior in ceremonial jaguar skin, claws, fierce character portrait',
            'char-14.jpg': 'Giant sloth with long claws, slow movement, prehistoric animal portrait',
        },
        'item': {
            'item-0.jpg': 'Golden sun disk artifact with engravings, treasure on dark background',
            'item-1.jpg': 'Carved jade mask with intricate patterns, ancient artifact on dark background',
            'item-2.jpg': 'Obsidian knife with sharp black blade, ceremonial weapon on dark background',
            'item-3.jpg': 'Feathered headdress with colorful plumes, ceremonial headwear on dark',
            'item-4.jpg': 'Ancient scroll with pictograms, bark paper, knowledge on dark background',
            'item-5.jpg': 'Gold and turquoise breastplate jewelry, treasure on dark background',
            'item-6.jpg': 'Carved stone calendar wheel with symbols, ancient on dark background',
            'item-7.jpg': 'Crystal skull with transparent quartz, mysterious on dark background',
            'item-8.jpg': 'Ceremonial drum with animal skin, carved wood on dark background',
            'item-9.jpg': 'Golden figurine of a deity, small statue on dark background',
            'item-10.jpg': 'Blowgun with darts, hunting weapon on dark background',
            'item-11.jpg': 'Jungle machete with wooden handle, cutting tool on dark background',
            'item-12.jpg': 'Ancient compass with unknown symbols, navigation on dark background',
            'item-13.jpg': 'Rope with vine material, natural fiber on dark background',
            'item-14.jpg': 'Crystal prism with glowing light inside, power source on dark',
        },
    },
}

Path('scripts/image_prompts.json').write_text(json.dumps(prompts, ensure_ascii=False))
print(f'Written {sum(len(v.get("bg",{})) + len(v.get("char",{})) + len(v.get("item",{})) for v in prompts.values())} prompts for {len(prompts)} themes')
